import Head from 'next/head';
import TopSection from '@src/components/pages/main/top-section';

export default function Home() {
  return (
    <div className='home'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopSection />
    </div>
  );
}
